sudo: required
services:
  - docker
before_install:
  - docker build -t tarundecipher/practice_ci -f Dockerfile.dev .

script:
  - docker run tarundecipher/practice_ci npm run test -- --coverage
